services:
  app:
    build: .                      # Usa o Dockerfile atual para construir a imagem
    command: ./.docker/start.sh    # Define o script que será executado ao iniciar o container
    ports:
      - 3000:3000                 # Mapeia a porta 3000 do container para a máquina local
    volumes:
      - .:/home/node/app 